version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-server
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  server:
    image: phonebook-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo-server:27017/the_database

volumes:
   mongo_data: 