version: '3.8'

services:
  app:
    image: phonebook-frontend-dev
    container_name: phonebook-frontend-dev
    build:
      context: ./phonebook-frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./phonebook-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3006:3006
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  mongo:
    image: mongo
    container_name: mongo-server
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./phonebook-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db


  server:
    image: phonebook-backend-dev
    container_name: phonebook-backend-dev
    build:
      context: ./phonebook-backend
      dockerfile: dev.Dockerfile
    ports:
      - 3001:3001
    volumes: 
      - ./phonebook-backend:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo-server:27017/the_database

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

volumes:
  mongo_data: