version: '3.8'

services:
  app:
    image: phonebook-frontend
    container_name: phonebook-frontend
    build:
      context: ./phonebook-frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read

  mongo:
    image: mongo
    container_name: mongo-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./phonebook-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db


  server:
    image: phonebook-backend
    container_name: phonebook-backend
    build:
      context: ./phonebook-backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo-server:27017/the_database

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

volumes:
  mongo_data: