version: '3.8'

services:
  app:
    image: phonebook-frontend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3006:3006
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3001